spring:
  application:
    name: user-service
  # Use Config Data API to import from Config Server
  config:
    import: "configserver:"
  cloud:
    config:
      # Config Server URI injected via environment variable
      uri: ${CONFIG_SERVER_URI}
      # Git branch/tag/commit label (defaults to main if not set)
      label: ${CONFIG_LABEL:main}
      # Fail fast if Config Server is unreachable (prod best practice)
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 2000
        multiplier: 1.6
        max-interval: 10000
      request-connect-timeout: 3000
      request-read-timeout: 3000
      # OAuth2 client credentials for Keycloak
      client:
        oauth2:
          client-id: ${CONFIG_CLIENT_ID}
          client-secret: ${CONFIG_CLIENT_SECRET}
          access-token-uri: ${KEYCLOAK_TOKEN_URI}
          grant-type: client_credentials

logging:
  level:
    org.springframework.cloud.config: TRACE
    org.springframework.web.client.RestTemplate: TRACE
    org.apache.http: TRACE
    org.apache.http.wire: TRACE
