spring:

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: MediaHubHikari
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000       # 30s
      idle-timeout: 600000            # 10m
      max-lifetime: 1800000           # 30m (keep < PG default 8h)
      #leak-detection-threshold: 20000 # 20s (optional; enable if diagnosing leaks)
      data-source-properties:
        reWriteBatchedInserts: true   # PostgreSQL batch insert optimization
        stringtype: unspecified       # Safer for Long/UUID/text casts

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true
    contexts: prod

  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 100
          time_zone: UTC
        order_inserts: true
        order_updates: true
        generate_statistics: false
        format_sql: false

#  cache:
#    type: caffeine
#    cache-names: auditEvents
#    caffeine:
#      spec: maximumSize=10000,expireAfterWrite=10m

  jackson:
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false

server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/plain,text/css,application/javascript
    min-response-size: 1KB

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      region: ${REGION:eu}
      environment: ${ENVIRONMENT:prod}
  observations:
    key-values:
      application: ${spring.application.name}
      region: ${REGION:eu}
      environment: ${ENVIRONMENT:prod}

logging:
  config: ${LOGGING_CONFIG_PATH:classpath:log4j2-spring.xml}
  level:
    root: INFO
    org.springframework.web: INFO                  # Web layer info only
    org.springframework.security: WARN             # Security events, not debug noise
    org.springframework.boot.autoconfigure: WARN  # Only warn on auto-config issues
    org.hibernate.SQL: INFO                        # Show SQL structure, not params
    org.hibernate.orm.jdbc.bind: OFF               # Don't log SQL params
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: WARN  # Show DB errors
    com.zaxxer.hikari: INFO                         # Connection pool lifecycle
    org.apache.catalina: WARN                       # Tomcat warnings only
    liquibase: INFO                                 # Migration summaries only
    liquibase.changelog: WARN                       # Only warn on changelog issues
    liquibase.executor: WARN                        # Execution warnings
    org.springframework.cache: WARN                 # Cache warnings
